# Generated by Django 5.1.6 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="battery_group",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="belt_part_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="color",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="coolant_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="engine",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="oil_spec",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="tire_size",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="trim",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
