# Generated by Django 5.1.6 on 2026-08-17 20:25

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_vehicle_specs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverprofile",
            name="home_latitude",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="driverprofile",
            name="home_longitude",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="notes",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="vehicles/",
                validators=[apps.core.validators.validate_image_size],
            ),
        ),
    ]
