# Generated by Django 5.1.6 on 2026-04-10 19:05

import uuid

from django.db import migrations, models


def fill_unique_phones(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for i, u in enumerate(User.objects.order_by("pk")):
        if (u.phone or "").strip():
            continue
        phone = f"+233900000{i:06d}"[:20]
        while User.objects.filter(phone=phone).exclude(pk=u.pk).exists():
            i += 1
            phone = f"+233900000{i:06d}"[:20]
        u.phone = phone
        u.save(update_fields=["phone"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "-created_at"],
                        name="accounts_ph_phone_ea13c2_idx",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.RunPython(fill_unique_phones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="phone number"
            ),
        ),
    ]
