# Generated by Django 5.1.6 on 2026-08-17 20:25

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_delete_emailotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                validators=[apps.core.validators.validate_image_size],
            ),
        ),
    ]
