[pytest]
DJANGO_SETTINGS_MODULE = autrifix.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = -ra --strict-markers
markers =
    django_db: Tests that use the database
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
