# Generated by Django 5.1.6 on 2026-04-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_seed_servicecategory_keywords"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "ordering": ["priority", "name"],
                "verbose_name_plural": "service categories",
            },
        ),
    ]
