# Generated by Django 5.1.6 on 2026-08-17 20:25

import django.core.validators
from django.db import migrations, models


def cancel_duplicate_live_jobs(apps, schema_editor) -> None:
    """Make existing data satisfy ``unique_live_job_per_service_request``.

    Acceptance was previously neither atomic nor locked, so a service request could
    already hold more than one non-cancelled job. Keep the earliest (the mechanic who
    actually won) and cancel the rest, so the constraint can be applied.
    """
    Job = apps.get_model("jobs", "Job")

    live = Job.objects.exclude(status="cancelled").order_by("service_request_id", "created_at")

    seen: set = set()
    duplicates: list = []
    for job in live.iterator():
        if job.service_request_id in seen:
            duplicates.append(job.pk)
        else:
            seen.add(job.service_request_id)

    if duplicates:
        Job.objects.filter(pk__in=duplicates).update(status="cancelled")


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_servicecategory_options"),
        ("mechanics", "0004_alter_mechanicprofile_base_latitude_and_more"),
    ]

    operations = [
        migrations.RunPython(cancel_duplicate_live_jobs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="job",
            name="notes",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="description",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="longitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("service_request",),
                name="unique_live_job_per_service_request",
            ),
        ),
    ]
