# Generated by Django 5.1.6 on 2026-08-18 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_rename_driver_and_mechanic_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="requires_destination",
            field=models.BooleanField(
                default=False,
                help_text="This service relocates the vehicle, so a request must say where to. Implies the job needs a tow-capable provider (SPEC-014 REQ-3).",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="destination_latitude",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="destination_longitude",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ],
            ),
        ),
    ]
