"""Money on the job, and quotes as a first-class record.

Adds the two-sided completion fields (``final_amount``, ``currency``, ``work_finished_at``)
and the ``awaiting_confirmation`` job state, plus the ``Quote`` model. Nothing is
backfilled: existing completed jobs predate the money model and honestly have no amount.

See ``specs/015-money-model.md`` and ``docs/DECISIONS.md`` ADR-022.
"""

# Generated by Django 5.1.6 on 2026-08-18 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_seed_requires_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="job",
            name="final_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="work_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_accept", "Pending accept"),
                    ("active", "Active"),
                    ("awaiting_confirmation", "Awaiting customer confirmation"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending_accept",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                ("notes", models.TextField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("job",),
                        name="unique_pending_quote_per_job",
                    )
                ],
            },
        ),
    ]
