"""State the sweeps need — SPEC-016.

``Job.auto_confirmed`` distinguishes a customer who agreed from one who went quiet, and
``ServiceRequestStatus.EXPIRED`` distinguishes a request nobody claimed from one somebody
cancelled. Both differences are lost if the existing values are reused.
"""

# Generated by Django 5.1.6 on 2026-08-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_money_and_quotes"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="auto_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("matching", "Matching"),
                    ("assigned", "Assigned"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
