# Generated by Django 5.1.6 on 2026-08-17 21:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("job.accepted", "Job accepted"),
                            ("job.transitioned", "Job status changed"),
                            ("request.cancelled", "Service request cancelled"),
                            ("auth.login_failed", "Failed login attempt"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=255)),
                (
                    "target_type",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit event",
                "verbose_name_plural": "audit events",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "-created_at"],
                        name="core_audite_target__692df1_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_audite_action_b37622_idx",
                    ),
                ],
            },
        ),
    ]
