# Generated by Django 5.1.6 on 2026-08-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("job.accepted", "Job accepted"),
                    ("job.transitioned", "Job status changed"),
                    ("request.cancelled", "Service request cancelled"),
                    ("auth.login_failed", "Failed login attempt"),
                    ("provider.verification_submitted", "Verification submitted"),
                    ("provider.verification_reviewed", "Verification reviewed"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
