# Generated by Django 5.1.6 on 2026-08-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="escrow_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("held", "Held"),
                    ("released", "Released to provider"),
                    ("refunded", "Refunded to customer"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
