# Generated by Django 5.1.6 on 2026-08-17 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mechanics",
            "0003_rename_mechanics_m_mechani_bf1fb6_idx_mechanics_m_mechani_327492_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mechanicprofile",
            name="base_latitude",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mechanicprofile",
            name="base_longitude",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mechanicprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
