# Generated by Django 5.1.6 on 2026-08-17 22:55

import apps.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanics", "0004_alter_mechanicprofile_base_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanicprofile",
            name="verification_level",
            field=models.CharField(
                choices=[
                    ("none", "Not verified"),
                    ("phone", "Phone verified"),
                    ("documents", "Documents verified"),
                    ("ghana_card", "Ghana Card verified"),
                ],
                db_index=True,
                default="none",
                help_text="Controls how precisely this mechanic sees driver locations (SPEC-013).",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MechanicVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requested_level",
                    models.CharField(
                        choices=[
                            ("none", "Not verified"),
                            ("phone", "Phone verified"),
                            ("documents", "Documents verified"),
                            ("ghana_card", "Ghana Card verified"),
                        ],
                        default="documents",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "id_document",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="verification/",
                        validators=[apps.core.validators.validate_image_size],
                    ),
                ),
                (
                    "selfie",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="verification/",
                        validators=[apps.core.validators.validate_image_size],
                    ),
                ),
                (
                    "workshop_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="verification/",
                        validators=[apps.core.validators.validate_image_size],
                    ),
                ),
                ("ghana_card_number", models.CharField(blank=True, max_length=32)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, max_length=2000)),
                (
                    "mechanic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="mechanics.mechanicprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-submitted_at"],
                        name="mechanics_m_status_986d9a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("mechanic",),
                        name="unique_pending_verification_per_mechanic",
                    )
                ],
            },
        ),
    ]
