# Generated by Django 5.1.6 on 2026-08-18 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanics", "0006_rename_mechanic_models_to_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="providerprofile",
            new_name="mechanics_p_is_avai_749f72_idx",
            old_name="mechanics_m_is_avai_b66978_idx",
        ),
        migrations.RenameIndex(
            model_name="providerverification",
            new_name="mechanics_p_status_1d0486_idx",
            old_name="mechanics_m_status_986d9a_idx",
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="providerprofile",
            name="verification_level",
            field=models.CharField(
                choices=[
                    ("none", "Not verified"),
                    ("phone", "Phone verified"),
                    ("documents", "Documents verified"),
                    ("ghana_card", "Ghana Card verified"),
                ],
                db_index=True,
                default="none",
                help_text="Controls how precisely this provider sees customer locations (SPEC-013).",
                max_length=20,
            ),
        ),
    ]
