# Generated by Django 5.1.6 on 2026-08-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mechanics",
            "0007_rename_mechanics_m_is_avai_b66978_idx_mechanics_p_is_avai_749f72_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="providerserviceoffering",
            name="per_km_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Towing rate per kilometre. Same currency caveat as hourly_rate.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="providerserviceoffering",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Labour rate. Currency is undecided platform-wide — see ADR-006.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
