# Generated by Django 5.1.6 on 2026-08-18 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mechanics", "0008_providerserviceoffering_per_km_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("mechanic", "Mechanic"),
                            ("tow", "Tow operator"),
                            ("both", "Mechanic and tow operator"),
                        ],
                        db_index=True,
                        default="mechanic",
                        max_length=20,
                    ),
                ),
                (
                    "verification_level",
                    models.CharField(
                        choices=[
                            ("none", "Not verified"),
                            ("phone", "Phone verified"),
                            ("documents", "Documents verified"),
                            ("ghana_card", "Ghana Card verified"),
                        ],
                        db_index=True,
                        default="none",
                        help_text="Granted to the business; inherited by its active members.",
                        max_length=20,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("registration_number", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "agencies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgencyMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("operator", "Operator"),
                        ],
                        default="operator",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("removed", "Removed"),
                        ],
                        db_index=True,
                        default="invited",
                        max_length=20,
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="mechanics.agency",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="mechanics.providerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-invited_at"],
                "indexes": [
                    models.Index(
                        fields=["agency", "status"],
                        name="mechanics_a_agency__b9c5b6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "removed"), _negated=True),
                        fields=("provider",),
                        name="one_live_agency_membership_per_provider",
                    )
                ],
            },
        ),
    ]
