# Generated by Django 5.1.6 on 2026-08-17 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_job_notes_alter_servicerequest_description_and_more"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["job"], name="reviews_rev_job_id_45562c_idx"),
        ),
    ]
