# Generated by Django 5.1.6 on 2026-04-10 17:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MechanicProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("base_latitude", models.FloatField(blank=True, null=True)),
                ("base_longitude", models.FloatField(blank=True, null=True)),
                ("service_radius_km", models.PositiveIntegerField(default=25)),
                ("is_available", models.BooleanField(db_index=True, default=False)),
                (
                    "rating_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanic_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-rating_avg", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_available"], name="mechanics_m_is_avai_b66978_idx"
                    )
                ],
            },
        ),
    ]
