# Generated by Django 5.1.6 on 2026-04-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mechanics", "0002_mechanicserviceoffering"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mechanicserviceoffering",
            new_name="mechanics_m_mechani_327492_idx",
            old_name="mechanics_m_mechani_bf1fb6_idx",
        ),
    ]
