# Generated by Django 5.1.6 on 2026-08-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="body",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("request.accepted", "A mechanic accepted your request"),
                    ("job.active", "Your mechanic has started"),
                    ("job.completed", "Job completed"),
                    ("job.cancelled", "Job cancelled"),
                    ("request.cancelled", "Request cancelled"),
                    ("review.received", "You received a review"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
