# Generated by Django 5.1.6 on 2026-08-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("request.accepted", "A provider accepted your request"),
                    ("job.active", "Your provider has started"),
                    ("job.completed", "Job completed"),
                    ("job.cancelled", "Job cancelled"),
                    ("request.cancelled", "Request cancelled"),
                    ("review.received", "You received a review"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
