# Generated by Django 5.1.6 on 2026-08-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("request.accepted", "A provider accepted your request"),
                    ("job.active", "Your provider has started"),
                    ("quote.submitted", "You received a price quote"),
                    ("quote.accepted", "Your quote was accepted"),
                    ("quote.declined", "Your quote was declined"),
                    ("job.awaiting_confirmation", "Confirm the work and amount"),
                    ("job.completed", "Job completed"),
                    ("job.cancelled", "Job cancelled"),
                    ("request.cancelled", "Request cancelled"),
                    ("review.received", "You received a review"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
