# Generated by Django 5.1.6 on 2026-08-17 20:25

import apps.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="body",
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="chat/",
                validators=[apps.core.validators.validate_image_size],
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "-created_at"], name="chat_chatme_room_id_df087f_idx"
            ),
        ),
    ]
